### ISSUE TITLE
temperature and humidity conversion not exact

### ISSUE THREAD

**Issue by fishingpole** [Sensirion/arduino-i2c-scd4x#17] opened 2022-06-15 17:53 UTC
File SensirionI2CScd4x.cpp, function readMeasurement() uses 65536.0 in the conversion formulas from temperature ticks to temperature degrees C and for humidity ticks to humidity RH.

The SCD4x Datasheet Table 11 in section 3.5.2 says to use "2^16 - 1" which would be 65535.0.

**Comment by psachs** [comment] 2022-06-28 11:28
thank you for reporting. The issue is fixed in master

**Closed by psachs** 2022-06-28 11:28 UTC
